//! AudioCapture implementation for Apple platforms via raw CoreAudio FFI.
//!
//! Builds the input AudioUnit directly using objc2-audio-toolbox C functions.
//! The fix for kAudioUnitErr_InvalidPropertyValue (-10851) on physical iPhone:
//! coreaudio-rs calls AudioUnitInitialize inside its constructor; on device,
//! any property set after initialize (EnableIO, stream format) fails. Here we
//! configure FIRST, then initialize.
//!
//! # Raw open() sequence (all before AudioUnitInitialize)
//!
//! a. AudioComponentDescription { type=Output, subType=RemoteIO|HALOutput, mfr=Apple }
//! b. AudioComponentFindNext(null, &desc) → component
//! c. AudioComponentInstanceNew(component, &mut unit)  ← NO initialize yet
//! d. macOS only: warm-up init → CurrentDevice (scope Global, element 0) →
//!    EnableIO input=1 (scope Input=1, element 1) →
//!    DisableIO output=0 (scope Output=2, element 0) → uninit.
//!    Both CurrentDevice and EnableIO require an initialized unit (-10851
//!    otherwise). Both survive uninitialize.
//!    iOS RemoteIO: EnableIO/DisableIO on the uninitialized unit, no CurrentDevice.
//! e. kAudioUnitProperty_StreamFormat on (scope Output=2, element 1): interleaved F32
//! f. kAudioUnitProperty_ShouldAllocateBuffer = 0 on (scope Output, element 1)
//! g. Set kAudioOutputUnitProperty_SetInputCallback (scope Global, element 0)
//! h. AudioUnitInitialize(unit)  ← NOW, after all config
//! i. AudioOutputUnitStart(unit)

use crate::devices::AppleStreamHandle;
use domain_ports::audio_capture::{
    AudioCapture, CaptureCallback, CaptureConfig, CaptureError, CaptureFrame, CaptureSession,
    LifecycleSink,
};
use domain_ports::audio_devices::StreamHandle;
use domain_ports::clock::Clock;
#[cfg(target_os = "macos")]
use objc2_audio_toolbox::{kAudioOutputUnitProperty_CurrentDevice, kAudioUnitSubType_HALOutput};
use objc2_audio_toolbox::{
    kAudioOutputUnitProperty_EnableIO, kAudioOutputUnitProperty_SetInputCallback,
    kAudioUnitManufacturer_Apple, kAudioUnitProperty_ShouldAllocateBuffer,
    kAudioUnitProperty_StreamFormat, kAudioUnitType_Output, AURenderCallbackStruct,
    AudioComponentDescription, AudioComponentFindNext, AudioComponentInstanceDispose,
    AudioComponentInstanceNew, AudioOutputUnitStart, AudioOutputUnitStop, AudioUnit,
    AudioUnitInitialize, AudioUnitRender, AudioUnitRenderActionFlags, AudioUnitSetProperty,
    AudioUnitUninitialize,
};
use objc2_core_audio_types::{
    kAudioFormatFlagIsFloat, kAudioFormatFlagIsPacked, kAudioFormatLinearPCM, AudioBuffer,
    AudioBufferList, AudioStreamBasicDescription, AudioTimeStamp,
};
use std::os::raw::c_void;
use std::ptr::NonNull;
use std::sync::Arc;

/// FourCC 'rioc' — kAudioUnitSubType_RemoteIO from Apple's AUComponent.h.
/// Not generated by objc2-audio-toolbox 0.3.2. Value verified against the
/// iOS SDK header: 'r'=0x72 'i'=0x69 'o'=0x6f 'c'=0x63.
#[cfg(target_os = "ios")]
const K_AUDIO_UNIT_SUBTYPE_REMOTE_IO: u32 = 0x7269_6f63;

/// kAudioUnitScopeGlobal = 0
const K_SCOPE_GLOBAL: u32 = 0;
/// kAudioUnitScopeInput = 1
const K_SCOPE_INPUT: u32 = 1;
/// kAudioUnitScopeOutput = 2
const K_SCOPE_OUTPUT: u32 = 2;

/// Build an Apple-native `AudioCapture`. The `clock` stamps `t_ms` on
/// every delivered frame. Cheap construction — opens nothing until
/// [`AudioCapture::open`].
pub fn new(clock: Arc<dyn Clock>) -> impl AudioCapture {
    AppleAudioCapture { clock }
}

struct AppleAudioCapture {
    clock: Arc<dyn Clock>,
}

impl AudioCapture for AppleAudioCapture {
    fn negotiate(
        &self,
        handle: &StreamHandle,
        requested: &CaptureConfig,
    ) -> Result<CaptureConfig, CaptureError> {
        handle
            .0
            .downcast_ref::<AppleStreamHandle>()
            .ok_or(CaptureError::InvalidHandle)?;

        // Reject absurd configs early.
        if requested.channels == 0 || requested.channels > 64 {
            return Err(CaptureError::UnsupportedConfig {
                wanted: requested.clone(),
                actual: None,
            });
        }
        if requested.sample_rate == 0 {
            return Err(CaptureError::UnsupportedConfig {
                wanted: requested.clone(),
                actual: None,
            });
        }

        negotiate_impl(requested)
    }

    fn open(
        &self,
        handle: StreamHandle,
        cfg: CaptureConfig,
        on_frame: CaptureCallback,
        _on_event: LifecycleSink,
    ) -> Result<CaptureSession, CaptureError> {
        // Reject absurd configs (guard against callers that bypass negotiate).
        if cfg.channels == 0 || cfg.channels > 64 {
            return Err(CaptureError::UnsupportedConfig {
                wanted: cfg.clone(),
                actual: None,
            });
        }
        if cfg.sample_rate == 0 {
            return Err(CaptureError::UnsupportedConfig {
                wanted: cfg.clone(),
                actual: None,
            });
        }

        let apple = handle
            .0
            .downcast_ref::<AppleStreamHandle>()
            .ok_or(CaptureError::InvalidHandle)?;

        let clock = Arc::clone(&self.clock);

        #[cfg(target_os = "ios")]
        let guard = {
            let _ = apple; // unit struct on iOS; device_id not needed
            build_input_unit(apple, &cfg, on_frame, clock)?
        };

        #[cfg(target_os = "macos")]
        let guard = build_input_unit(apple, &cfg, on_frame, clock)?;

        Ok(CaptureSession::new(move || drop(guard)))
    }
}

// -----------------------------------------------------------------
// negotiate: read back the live AVAudioSession rate (iOS) or accept
// the requested rate (macOS — AudioUnit handles it).
// -----------------------------------------------------------------

#[cfg(target_os = "ios")]
fn negotiate_impl(requested: &CaptureConfig) -> Result<CaptureConfig, CaptureError> {
    use objc2_avf_audio::AVAudioSession;

    let session = unsafe { AVAudioSession::sharedInstance() };
    // Set preferred rate; ignore error — we read back the actual.
    let _ = unsafe { session.setPreferredSampleRate_error(requested.sample_rate as f64) };
    let actual_rate = unsafe { session.sampleRate() };
    let sample_rate = if actual_rate > 0.0 {
        actual_rate.round() as u32
    } else {
        requested.sample_rate
    };

    // iOS exposes the live channel count via the session.
    let channels_raw = unsafe { session.inputNumberOfChannels() } as isize;
    let channels = if channels_raw >= 1 {
        (channels_raw as u16).min(requested.channels)
    } else {
        requested.channels
    };

    Ok(CaptureConfig {
        sample_rate,
        channels,
        buffer_frames: requested.buffer_frames,
    })
}

#[cfg(target_os = "macos")]
fn negotiate_impl(requested: &CaptureConfig) -> Result<CaptureConfig, CaptureError> {
    // macOS: accept the requested config; the AudioUnit will adapt to the
    // default input device's actual rate at initialize() time.
    Ok(CaptureConfig {
        sample_rate: requested.sample_rate,
        channels: requested.channels,
        buffer_frames: requested.buffer_frames,
    })
}

// -----------------------------------------------------------------
// CallbackState: heap-allocated, owned by UnitGuard via raw pointer.
// -----------------------------------------------------------------

struct CallbackState {
    unit: AudioUnit, // needed for AudioUnitRender pull
    on_frame: CaptureCallback,
    clock: Arc<dyn Clock>,
    buf: Vec<f32>, // reusable; sized to 4096*channels at open
    channels: u32,
}

// -----------------------------------------------------------------
// RAII teardown wrapper for the AudioUnit + CallbackState.
// -----------------------------------------------------------------

struct UnitGuard {
    unit: AudioUnit,
    state_ptr: *mut CallbackState, // freed in Drop
}

impl Drop for UnitGuard {
    fn drop(&mut self) {
        unsafe {
            AudioOutputUnitStop(self.unit);
            AudioUnitUninitialize(self.unit);
            AudioComponentInstanceDispose(self.unit);
            // Reclaim the boxed state. Safe: the unit is stopped so the
            // callback cannot fire after AudioOutputUnitStop returns.
            drop(Box::from_raw(self.state_ptr));
        }
    }
}

unsafe impl Send for UnitGuard {}

// -----------------------------------------------------------------
// Input callback trampoline (called from CoreAudio's I/O thread).
// -----------------------------------------------------------------

unsafe extern "C-unwind" fn input_trampoline(
    in_ref_con: NonNull<c_void>,
    io_action_flags: NonNull<AudioUnitRenderActionFlags>,
    in_time_stamp: NonNull<AudioTimeStamp>,
    in_bus_number: u32,
    in_number_frames: u32,
    _io_data: *mut AudioBufferList,
) -> i32 {
    // Safety: refcon is the Box<CallbackState> pointer kept alive by UnitGuard.
    let state = &mut *(in_ref_con.as_ptr() as *mut CallbackState);

    let channels = state.channels as usize;
    let needed = in_number_frames as usize * channels;
    if state.buf.len() < needed {
        state.buf.resize(needed, 0.0f32);
    }

    // AudioBufferList on the stack; point its buffer at our reusable Vec.
    let mut abl = AudioBufferList {
        mNumberBuffers: 1,
        mBuffers: [AudioBuffer {
            mNumberChannels: state.channels,
            mDataByteSize: (needed * std::mem::size_of::<f32>()) as u32,
            mData: state.buf.as_mut_ptr() as *mut c_void,
        }],
    };

    let status = AudioUnitRender(
        state.unit,
        io_action_flags.as_ptr(),
        in_time_stamp,
        in_bus_number,
        in_number_frames,
        NonNull::new_unchecked(&mut abl),
    );

    if status != 0 {
        // Log the first render error only (atomic flag avoids per-frame overhead).
        use std::sync::atomic::{AtomicBool, Ordering};
        static LOGGED: AtomicBool = AtomicBool::new(false);
        if !LOGGED.swap(true, Ordering::Relaxed) {
            eprintln!("[audio-apple] AudioUnitRender error: OSStatus {status}");
        }
        return 0; // noErr — don't propagate render errors; just skip frame
    }

    let t_ms = state.clock.now_ms();
    (state.on_frame)(CaptureFrame {
        samples: &state.buf[..needed],
        frames: in_number_frames as usize,
        t_ms,
    });

    0 // noErr
}

// -----------------------------------------------------------------
// Platform subtype helper
// -----------------------------------------------------------------

#[cfg(target_os = "ios")]
fn platform_subtype() -> u32 {
    K_AUDIO_UNIT_SUBTYPE_REMOTE_IO
}

#[cfg(target_os = "macos")]
fn platform_subtype() -> u32 {
    kAudioUnitSubType_HALOutput
}

// -----------------------------------------------------------------
// build_input_unit: the spec-ordered call sequence.
// Steps labeled to match the module-doc invariant list.
// -----------------------------------------------------------------

fn build_input_unit(
    #[cfg(target_os = "macos")] handle: &AppleStreamHandle,
    #[cfg(target_os = "ios")] _handle: &AppleStreamHandle,
    cfg: &CaptureConfig,
    on_frame: CaptureCallback,
    clock: Arc<dyn Clock>,
) -> Result<UnitGuard, CaptureError> {
    let channels = cfg.channels as u32;
    let bytes_per_frame = 4 * channels;

    unsafe {
        // a–b. Find the platform AudioUnit component.
        let desc = AudioComponentDescription {
            componentType: kAudioUnitType_Output,
            componentSubType: platform_subtype(),
            componentManufacturer: kAudioUnitManufacturer_Apple,
            componentFlags: 0,
            componentFlagsMask: 0,
        };
        let component = AudioComponentFindNext(std::ptr::null_mut(), NonNull::from(&desc));
        if component.is_null() {
            return Err(CaptureError::DeviceUnavailable {
                reason: "AudioComponentFindNext returned null".to_string(),
            });
        }

        // c. Create instance — no initialize yet
        let mut unit: AudioUnit = std::ptr::null_mut();
        let status = AudioComponentInstanceNew(component, NonNull::new_unchecked(&mut unit));
        if status != 0 || unit.is_null() {
            return Err(CaptureError::DeviceUnavailable {
                reason: format!("AudioComponentInstanceNew: OSStatus {status}"),
            });
        }

        // d. macOS HALOutput: warm-up init → CurrentDevice + EnableIO → uninit.
        //    Both CurrentDevice and EnableIO require the unit to be initialized
        //    (setting either on an uninitialized unit returns -10851). A brief
        //    init/uninit cycle connects the HAL server so these properties can be
        //    set. Both properties survive AudioUnitUninitialize.
        //    iOS RemoteIO must NOT do this (premature init is the root iOS bug).
        #[cfg(target_os = "macos")]
        {
            let s = AudioUnitInitialize(unit);
            if s != 0 {
                AudioComponentInstanceDispose(unit);
                return Err(CaptureError::DeviceUnavailable {
                    reason: format!("warm-up AudioUnitInitialize: OSStatus {s}"),
                });
            }

            // EnableIO must be set before CurrentDevice: the HAL requires the
            // input bus to be enabled before it will accept a CurrentDevice change.
            let enable: u32 = 1;
            let s = AudioUnitSetProperty(
                unit,
                kAudioOutputUnitProperty_EnableIO,
                K_SCOPE_INPUT,
                1,
                &enable as *const u32 as *const c_void,
                std::mem::size_of::<u32>() as u32,
            );
            if s != 0 {
                AudioUnitUninitialize(unit);
                AudioComponentInstanceDispose(unit);
                return Err(CaptureError::DeviceUnavailable {
                    reason: format!("EnableIO input: OSStatus {s}"),
                });
            }
            let disable: u32 = 0;
            let s = AudioUnitSetProperty(
                unit,
                kAudioOutputUnitProperty_EnableIO,
                K_SCOPE_OUTPUT,
                0,
                &disable as *const u32 as *const c_void,
                std::mem::size_of::<u32>() as u32,
            );
            if s != 0 {
                AudioUnitUninitialize(unit);
                AudioComponentInstanceDispose(unit);
                return Err(CaptureError::DeviceUnavailable {
                    reason: format!("DisableIO output: OSStatus {s}"),
                });
            }

            // Bind to the specific input device. Without CurrentDevice, the HAL
            // unit has no device to pull from and AudioUnitRender delivers zero frames.
            // Must be set AFTER EnableIO input (HAL requires input bus enabled first).
            let device_id: u32 = handle.device_id;
            let s = AudioUnitSetProperty(
                unit,
                kAudioOutputUnitProperty_CurrentDevice,
                K_SCOPE_GLOBAL,
                0,
                &device_id as *const u32 as *const c_void,
                std::mem::size_of::<u32>() as u32,
            );
            if s != 0 {
                AudioUnitUninitialize(unit);
                AudioComponentInstanceDispose(unit);
                return Err(CaptureError::DeviceUnavailable {
                    reason: format!("CurrentDevice: OSStatus {s}"),
                });
            }

            // All HAL properties set; uninitialize before the real config pass.
            // CurrentDevice and EnableIO both survive uninitialize.
            AudioUnitUninitialize(unit);
        }

        // e. iOS: EnableIO input=1 / output=0 on a fresh (uninitialized) RemoteIO unit.
        #[cfg(target_os = "ios")]
        {
            let enable: u32 = 1;
            let s = AudioUnitSetProperty(
                unit,
                kAudioOutputUnitProperty_EnableIO,
                K_SCOPE_INPUT,
                1,
                &enable as *const u32 as *const c_void,
                std::mem::size_of::<u32>() as u32,
            );
            if s != 0 {
                AudioComponentInstanceDispose(unit);
                return Err(CaptureError::DeviceUnavailable {
                    reason: format!("EnableIO input: OSStatus {s}"),
                });
            }
            let disable: u32 = 0;
            let s = AudioUnitSetProperty(
                unit,
                kAudioOutputUnitProperty_EnableIO,
                K_SCOPE_OUTPUT,
                0,
                &disable as *const u32 as *const c_void,
                std::mem::size_of::<u32>() as u32,
            );
            if s != 0 {
                AudioComponentInstanceDispose(unit);
                return Err(CaptureError::DeviceUnavailable {
                    reason: format!("DisableIO output: OSStatus {s}"),
                });
            }
        }

        // f. Stream format — interleaved F32 on (scope Output, element 1).
        //    "Output scope, element 1" = the output side of the input bus,
        //    i.e. the format delivered TO our callback.
        let asbd = AudioStreamBasicDescription {
            mSampleRate: cfg.sample_rate as f64,
            mFormatID: kAudioFormatLinearPCM,
            mFormatFlags: kAudioFormatFlagIsFloat | kAudioFormatFlagIsPacked,
            mBytesPerPacket: bytes_per_frame,
            mFramesPerPacket: 1,
            mBytesPerFrame: bytes_per_frame,
            mChannelsPerFrame: channels,
            mBitsPerChannel: 32,
            mReserved: 0,
        };
        let s = AudioUnitSetProperty(
            unit,
            kAudioUnitProperty_StreamFormat,
            K_SCOPE_OUTPUT,
            1,
            &asbd as *const AudioStreamBasicDescription as *const c_void,
            std::mem::size_of::<AudioStreamBasicDescription>() as u32,
        );
        if s != 0 {
            AudioComponentInstanceDispose(unit);
            return Err(CaptureError::UnsupportedConfig {
                wanted: cfg.clone(),
                actual: None,
            });
        }

        // g. Don't let the unit allocate its own input buffer; we provide
        //    the ABL in the callback and pull via AudioUnitRender.
        let no_alloc: u32 = 0;
        AudioUnitSetProperty(
            unit,
            kAudioUnitProperty_ShouldAllocateBuffer,
            K_SCOPE_OUTPUT,
            1,
            &no_alloc as *const u32 as *const c_void,
            std::mem::size_of::<u32>() as u32,
        );

        // h. Install input callback (SetInputCallback, scope Global, element 0).
        let init_capacity = 4096 * channels as usize;
        let state = Box::new(CallbackState {
            unit,
            on_frame,
            clock,
            buf: vec![0.0f32; init_capacity],
            channels,
        });
        let state_ptr = Box::into_raw(state);

        let cbs = AURenderCallbackStruct {
            inputProc: Some(input_trampoline),
            inputProcRefCon: state_ptr as *mut c_void,
        };
        let s = AudioUnitSetProperty(
            unit,
            kAudioOutputUnitProperty_SetInputCallback,
            K_SCOPE_GLOBAL,
            0,
            &cbs as *const AURenderCallbackStruct as *const c_void,
            std::mem::size_of::<AURenderCallbackStruct>() as u32,
        );
        if s != 0 {
            drop(Box::from_raw(state_ptr));
            AudioComponentInstanceDispose(unit);
            return Err(CaptureError::DeviceUnavailable {
                reason: format!("SetInputCallback: OSStatus {s}"),
            });
        }

        // i. Initialize — NOW, after all config
        let s = AudioUnitInitialize(unit);
        if s != 0 {
            drop(Box::from_raw(state_ptr));
            AudioComponentInstanceDispose(unit);
            return Err(CaptureError::DeviceUnavailable {
                reason: format!("AudioUnitInitialize: OSStatus {s}"),
            });
        }

        // j. Start
        let s = AudioOutputUnitStart(unit);
        if s != 0 {
            AudioUnitUninitialize(unit);
            drop(Box::from_raw(state_ptr));
            AudioComponentInstanceDispose(unit);
            return Err(CaptureError::DeviceUnavailable {
                reason: format!("AudioOutputUnitStart: OSStatus {s}"),
            });
        }

        Ok(UnitGuard { unit, state_ptr })
    }
}
